module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-dim": "#9c48ea",
        "surface-dim": "#060e20",
        "error-container": "#a70138",
        "on-error": "#490013",
        "on-primary": "#0f00a4",
        "surface-container-high": "#141f38",
        "on-background": "#dee5ff",
        "secondary": "#c180ff",
        "error": "#ff6e84",
        "secondary-container": "#6f00be",
        "on-secondary-fixed": "#4f0089",
        "inverse-surface": "#faf8ff",
        "inverse-on-surface": "#4d556b",
        "secondary-fixed": "#e5c6ff",
        "primary-container": "#9396ff",
        "surface-container-highest": "#192540",
        "primary-fixed-dim": "#8387ff",
        "surface-container-lowest": "#000000",
        "on-secondary-container": "#e9cdff",
        "on-secondary": "#33005b",
        "on-tertiary": "#4b002a",
        "primary": "#a3a6ff",
        "tertiary-fixed": "#ff8cbc",
        "surface-tint": "#a3a6ff",
        "primary-dim": "#6063ee",
        "on-primary-fixed-variant": "#0e009d",
        "on-secondary-fixed-variant": "#7511c3",
        "outline": "#6d758c",
        "secondary-fixed-dim": "#dbb4ff",
        "on-tertiary-fixed-variant": "#740044",
        "inverse-primary": "#494bd7",
        "surface": "#060e20",
        "tertiary-fixed-dim": "#ff73b1",
        "on-surface-variant": "#a3aac4",
        "background": "#060e20",
        "tertiary": "#ff6daf",
        "on-tertiary-fixed": "#37001d",
        "surface-container": "#0f1930",
        "on-primary-fixed": "#000000",
        "outline-variant": "#40485d",
        "surface-bright": "#1f2b49",
        "on-surface": "#dee5ff",
        "tertiary-dim": "#ff67ad",
        "primary-fixed": "#9396ff",
        "surface-container-low": "#091328",
        "on-tertiary-container": "#2f0018",
        "error-dim": "#d73357",
        "on-primary-container": "#0a0081",
        "on-error-container": "#ffb2b9",
        "tertiary-container": "#fa53a4",
        "surface-variant": "#192540"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Manrope"]
      },
    },
  },
  plugins: [],
};
